<?php

use Illuminate\Database\Seeder;

class category_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('category')->delete();

      $category = [
        ["category_name" => "BanG Dream!", "category_folder" => "LedakaN Impian! (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 2wei! Herz", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 2! Inti (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Grisaia no Rakuen", "category_folder" => "Nirwana Kelabu (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Rio - Rainbow Gate", "category_folder" => "Rio - Gerbang Pelangi! (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "HUNTERxHUNTER 2011", "category_folder" => "PEMBURUxPEMBURU 2011 (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "ReLIFE", "category_folder" => "Mengulang Kehidupan (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Yozakura Quartet - Hoshi no Umi", "category_folder" => "Kuartet Yozakura - Bintang dari Laut (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Yozakura Quartet - Hana no Uta", "category_folder" => "Kuartet Yozakura - Lagu Bunga (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Zutto Mae Kara Suki Deshita - Kokuhaku Jikko Inkai", "category_folder" => "Sudah Sejak Lama Aku Mencintaimu (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Tasogare Otome x Amnesia", "category_folder" => "Gadis Senja x Hilang Ingatan (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Taboo Tattoo", "category_folder" => "Tato Tabu (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Shiki", "category_folder" => "Mayat Iblis (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sengoku Basara", "category_folder" => "Era Perang Basara (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sekai Seifuku - Bouryaku no Zvezda", "category_folder" => "PLOT Zvezda - Penaklukan Dunia (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Red Data Girl", "category_folder" => "Gadis Data Merah (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ore no Kanojo to Osananajimi ga Shuraba Sugiru", "category_folder" => "Medan Perang Pacarku dan Teman Kecilku (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ore no Kanojo to Osananajimi ga Shuraba Sugiru", "category_folder" => "Medan Perang Pacarku dan Teman Kecilku (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ore no Imouto ga Konna ni Kawaii Wake ga Nai", "category_folder" => "Tidak Mungkin Adik Perempuanku Seimut Ini (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Alderamin on the Sky", "category_folder" => "Alderamin di Surga (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Nerawareta Gakuen", "category_folder" => "Akademi Supernatural (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Mitsudomoe Zouryouchuu!", "category_folder" => "Kembar 3 Yang Semakin Rusuh (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Medaka Box", "category_folder" => "Kotak Medaka (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Mayo Chiki!", "category_folder" => "Ayam Nyasar! (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 3rei!", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 3! (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Unbreakable Machine-Doll", "category_folder" => "Boneka yang Mustahil Hancur (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Level E", "category_folder" => "Level E (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kotonoha no Niwa", "category_folder" => "Taman Harfiah (BD)", "category_type" => 2, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kono Bijutsubu ni ha Mondai ga Aru!", "category_folder" => "Ada Masalah di Klub Seni! (TV)",  "category_type" => 1, "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kokoro Connect", "category_folder" => "Sambung Hati (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Himouto! Umaruchan", "category_folder" => "Adik Bermuka Dua! Si Umar (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Himouto! Umaruchan", "category_folder" => "Adik Bermuka Dua! Si Umar (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Danna ga Nani wo Itteiru ka Wakaranai Ken", "category_folder" => "Aku Tidak Mengerti Perkataan Suamiku (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Danna ga Nani wo Itteiru ka Wakaranai Ken S2", "category_folder" => "Aku Tidak Mengerti Perkataan Suamiku S2 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Boku wa Tomodachi ga Sukunai", "category_folder" => "Aku Tidak Punya Banyak Teman + NEXT (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Boku wa Tomodachi ga Sukunai NEXT", "category_folder" => "Aku Tidak Punya Banyak Teman + NEXT (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Keppeki Danshi Aoyamakun", "category_folder" => "Aoyama Si Gila Kebersihan (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "FREE!", "category_folder" => "BEBAS! (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Saikin, Imouto no Yousu ga Chotto Okashiinda ga.", "category_folder" => "Belakangan Ini Adikku Bersikap Aneh (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Glasslip", "category_folder" => "Bibir Kaca (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Blade", "category_folder" => "Bilah Si Botak (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Blame The Movie", "category_folder" => "Blame - Peninggalan Kota Terminal (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Grisaia no Kajitsu", "category_folder" => "Buah Kelabu (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ano hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai", "category_folder" => "Bunga Itu (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Glass no Hana to Kowasu Sekai", "category_folder" => "Bunga Kaca dan Kehancuran Dunia (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka", "category_folder" => "Cari Jodoh di Dungeon (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden - Sword Oratoria", "category_folder" => "Cari Jodoh di Dungeon - Pedang Oratoria (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Log Horizon", "category_folder" => "Catatan Cakrawala (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Aho Girl", "category_folder" => "Cewek Bego (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "BTOOOM!", "category_folder" => "DUAAAR! (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Blood-C", "category_folder" => "Darah Cecek (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Blood-C - The Last Dark", "category_folder" => "Darah Cecek - Kegelapan Terakhir (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Papa no Iukoto wo Kikinasai!", "category_folder" => "Dengarkan Perkataan Papa!!! (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kyoukai no Kanata", "category_folder" => "Di Balik Batas (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kyoukai no Kanata", "category_folder" => "Di Balik Batas + Pengadilan Idola (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Rakuen Tsuihou - Expelled from Paradise", "category_folder" => "Diasingkan dari Surga (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ao no Exorcist", "category_folder" => "Dukun Biru (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ao no Exorcist S2", "category_folder" => "Dukun Biru S2 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Musaigen no Phantom World", "category_folder" => "Dunia Bayangan Segudang Warna (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Musaigen no Phantom World", "category_folder" => "Dunia Bayangan Segudang Warna (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Another", "category_folder" => "Dunia Lain (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai", "category_folder" => "Dunia Membosankan Tanpa Lawakan Kotor (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fairy Tail (2014)", "category_folder" => "Ekor Peri 2014 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sora no Otoshimono - Tokeijikake no Angeloid", "category_folder" => "Film Layar Lebar Barang Jatuh dari Langit (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sora no Otoshimono - Eien no Watashi no Torikago", "category_folder" => "Film Layar Lebar Barang Jatuh dari Langit (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ano hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai - Menma he no Tegami", "category_folder" => "Film Layar Lebar Bunga Itu - Surat Untuk Menma (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kyoukai no Kanata Movie -I'll be here-", "category_folder" => "Film Layar Lebar Di Balik Batas (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fairy Tail The Movie - Houou no Miko", "category_folder" => "Film Layar Lebar Ekor Peri - Pendeta Feniks (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "The Last - Naruto the Movie", "category_folder" => "Film Layar Lebar Naruto - Terakhir (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Hibike! Sound! Euphonium the Movie", "category_folder" => "Film Layar Lebar Suarakan! Eufonium (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/stay night: Unlimited Blade Works (Movie)", "category_folder" => "Film Layar Lebar Takdir begadang semalam UBW (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "PERSONA 3 THE MOVIE", "category_folder" => "Film Layar Lebar Topeng 3 (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ookami Shoujo to Kuro Ouji", "category_folder" => "Gadis Serigala dan Pangeran Hitam (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Tokyo Ravens", "category_folder" => "Gagak-Gagak Tokyo (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Galilei Donna", "category_folder" => "Galilei Perempuan (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Gantz:O", "category_folder" => "Gantz O (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Harmony", "category_folder" => "Harmoni (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ryuugajou Nanana no Maizoukin", "category_folder" => "Harta Terpendam Nanana (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Tales of Zestiria the X", "category_folder" => "Hikayat Zestiria X (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "ISUCA", "category_folder" => "ISUCA (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Eromanga Sensei", "category_folder" => "Ilustrator Eromanga (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Inari, Konkon, Koi Iroha.", "category_folder" => "Inari, Konkon, dan Warna Cinta (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Bokura wa Minna Kawaisou", "category_folder" => "Kami Semua Anak Kos-Kosan Kawai (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Re:Zero kara Hajimeru Isekai Seikatsu", "category_folder" => "Kehidupan di Dunia Lain Dimulai dari Nol (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Re:Zero kara Hajimeru Isekai Seikatsu", "category_folder" => "Kehidupan di Dunia Lain Dimulai dari Nol SP (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kokoro ga Sakebitagatterunda", "category_folder" => "Keinginan Hati Untuk Menjerit (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "K-ON! Movie", "category_folder" => "Keiong! Film Layar Lebar (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Monster Musume no Iru Nichijou", "category_folder" => "Keseharian Bersama Gadis Monster (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kantai Collection", "category_folder" => "Koleksi Armada Kapal (TV)) ",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kimi no Iru Machi", "category_folder" => "Kota Tempatmu Berada (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "FREE!", "category_folder" => "BEBAS! (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Mujaki no Rakuen", "category_folder" => "Kumpulan Kartun Sekali Tamat (OVA)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Pupa", "category_folder" => "Kumpulan Kartun Sekali Tamat (OVA)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Asa Made Jugyou Chu!", "category_folder" => "Kumpulan Kartun Sekali Tamat (OVA)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Grisaia no Meikyuu", "category_folder" => "Labirin Kelabu (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Hajimete no GAL", "category_folder" => "Lonte Pertamaku (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "One Punch Man", "category_folder" => "Manusia Satu Pukulan (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sakura Quest", "category_folder" => "Misi Sakura (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Tonari no Kaibutsukun", "category_folder" => "Monster di Sebelahku (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Mahouka Koukou no Rettousei", "category_folder" => "Murid Terbelakang di Sekolah Sihir (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kobayashi-san Chi no Maid Dragon", "category_folder" => "Naga Pelayan di Kediaman Kobayashi (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Naruto Shippuden Movie 5 - Blood Prison", "category_folder" => "Naruto Shippuden - Penjara Darah (DVD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Nagi no Asukara", "category_folder" => "Nikung Tanpa Ragu (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Gatchaman Crowds", "category_folder" => "Pahlawan Lintas Masyarakat (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Gatchaman Crowds Insight", "category_folder" => "Pahlawan Lintas Masyarakat S2 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Hentai Ouji to Warawanai Neko", "category_folder" => "Pangeran Cabul dan Kucing Batu (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kamisama Dolls", "category_folder" => "Para Boneka Dewa (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kiseijuu: Sei no Kakuritsu", "category_folder" => "Parasit (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Momo Kyun Sword", "category_folder" => "Pedang Tetek Momo (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "BLACK BULLET", "category_folder" => "Peluru Hitam (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Black Rock Shooter", "category_folder" => "Penembak Karang Hitam (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Maho Tsukai no Yome", "category_folder" => "Pengantin Sang Penyihir (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Seraph of the End", "category_folder" => "Penghabisan Seraph (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Seraph of the End: Battle in Nagoya", "category_folder" => "Penghabisan Seraph S2 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Rail Wars!", "category_folder" => "Perang Rel (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Golden Time", "category_folder" => "Periode Emas (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sakamoto desu ga?", "category_folder" => "Perkenalkan, Aku Sakamoto (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Akagami no Shirayukihime", "category_folder" => "Putri Salju Berambut Merah (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Akagami ni Shirayukihime", "category_folder" => "Putri Salju Berambut Merah (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Kuromukuro", "category_folder" => "Relik Hitam (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Highschool of The Dead", "category_folder" => "SMA Mayat (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sword Art Online", "category_folder" => "Seni Pedang Daring + Edisi Ekstra (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Sword Art Online II", "category_folder" => "Seni Pedang Daring II (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Amaama to Inazuma", "category_folder" => "Si Manis dan Petir (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Girl Friend BETA", "category_folder" => "Simulasi Teman Perempuan (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Hibike! Sound! Euphonium", "category_folder" => "Suarakan! Eufonium (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Hibike! Sound! Euphonium S2", "category_folder" => "Suarakan! Eufonium S2 (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/Zero", "category_folder" => "Takdir Hampa (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/Grand Order!", "category_folder" => "Takdir Perintah Agung (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/Grand Order", "category_folder" => "Takdir Perintah Agung (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 2wei", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 2! (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 2wei", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 2! (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 2wei Herz", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 2! Inti (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 2wei Herz", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 2! Inti (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/kaleid Prisma☆Illya 3wei", "category_folder" => "Takdir Tongkat Kaleid Prisma Illya 3! (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Fate/stay night [Unlimited Blade Works] (Serial)", "category_folder" => "Takdir begadang semalam [UBW] (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Ore no Imouto ga Konna ni Kawaii Wake ga Nai S2", "category_folder" => "Tidak Mungkin Adik Perempuanku Seimut Ini S2 (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Deadman Wonderland", "category_folder" => "Wahana Pidana Mati (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Wakaba Girl", "category_folder" => "Wakaba Gaul (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Dagashikashi", "category_folder" => "Warung Jajanan (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Dagashikashi", "category_folder" => "Warung Jajanan (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Koe no Katachi", "category_folder" => "Wujud Suara (BD)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Denki-gai no Honya-san", "category_folder" => "Pegawai Toko Buku Kota Elektrik (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Nozo x Kimi", "category_folder" => "Kumpulan Kartun Sekali Tamat (OVA)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Nozoki Ana", "category_folder" => "Kumpulan Kartun Sekali Tamat (OVA)",  "category_type" => 2,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
        ["category_name" => "Log Horizon 2", "category_folder" => "Catatan Cakrawala 2 (TV)",  "category_type" => 1,  "created_at" => date("Y-m-d H:i:s"), "updated_at" => date("Y-m-d H:i:s")],
      ];

      DB::table('category')->insert($category);
    }
}
